; Arborcore memory-copy policy metadata
;
; Threshold values themselves are generated by the memory
; qualification process and compiled into memory.asm.
;
; This object exposes the selected policy for diagnostics,
; tests, and future C/runtime integration.


%include "generated/memory_thresholds.inc"


%if MEMORY_COPY_QWORD_MIN < 1
    %error "MEMORY_COPY_QWORD_MIN must be at least 1"
%endif

%if MEMORY_COPY_REP_MIN <= MEMORY_COPY_QWORD_MIN
    %error "MEMORY_COPY_REP_MIN must exceed MEMORY_COPY_QWORD_MIN"
%endif


global memory_threshold_policy_version
global memory_threshold_qword_min
global memory_threshold_rep_min


section .rodata


align 8

memory_threshold_policy_version:
    dq 1


memory_threshold_qword_min:
    dq MEMORY_COPY_QWORD_MIN


memory_threshold_rep_min:
    dq MEMORY_COPY_REP_MIN


section .note.GNU-stack noalloc noexec nowrite progbits
