#!/usr/bin/env bash
set -euo pipefail

ROOT="${ARBORCORE_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
cd "$ROOT"
CONTRACT=application/arborcore-application-ddd-mvc-foundation-1.contract
[[ -s "$CONTRACT" ]]

required=(
  'ARBORCORE_APPLICATION_DDD_MVC_FOUNDATION_VERSION=0.1-AF0-AF1-R2-HTTP1'
  'AF_BASE_COMMIT=a8d23f77bea211e31bd404230f06c2bc6e8a33d1'
  'AF_BASE_TREE=3da07e77f2af6103e8f0bd8e3781c6000f8082a5'
  'AF_DEPENDENCY_DIRECTION=SOURCE_DEPENDENCIES_INWARD_RUNTIME_CALLS_BIDIRECTIONAL_BY_ABI'
  'AF_APPLICATION_TO_FRAMEWORK=PUBLIC_ARBORCORE_C_API_AND_STABLE_LOWER_CAPABILITIES'
  'AF_FRAMEWORK_TO_APPLICATION=REGISTERED_REQUEST_DISPATCH_CAPABILITY_ABI'
  'AF_LOWER_LAYER_HARDCODED_APPLICATION_POLICY=ZERO'
  'AF_DOMAIN_DIRECT_TRANSPORT_DEPENDENCY=PROHIBITED'
  'AF_DOMAIN_DIRECT_INFRASTRUCTURE_DEPENDENCY=PROHIBITED'
  'AF_ERROR_CHANNEL_1=MECHANISM_ARBOR_STATUS'
  'AF_ERROR_CHANNEL_2=BOUNDED_CONTEXT_TYPED_APPLICATION_DOMAIN_OUTCOME'
  'AF_ERROR_CHANNEL_3=PRESENTATION_RESPONSE_PLAN'
  'AF_REQUEST_SPANS=BORROWED_REQUEST_LIFETIME'
  'AF_REQUEST_ARENA=REQUEST_LIFETIME_OWNED_STORAGE'
  'AF_RESPONSE_BODY=BORROWED_MUST_OUTLIVE_SERIALIZATION'
  'AF_RESPONSE_PLAN_SUPPORTED_STATUSES=FINAL_200_599'
  'AF_CAPABILITIES_ABI_VERSION=1'
  'AF_CAPABILITY_CALLBACK_RETURN=ZERO_SUCCESS_NEGATIVE_MECHANISM_FAILURE_POSITIVE_RESERVED_REJECTED'
  'AF_GLOBAL_MUTABLE_CAPABILITY_REGISTRY=ZERO'
  'AF_FROZEN_BASELINE_SEMANTICS=QUALIFIED_BASELINE_CONTROLLED_REOPEN_ALLOWED'
  'AF_CONTROLLED_RETROFIT_POLICY=NECESSITY_MINIMAL_SCOPE_DEPENDENCY_REQUALIFICATION_REVIEW'
  'AF0_AF1_LOWER_LAYER_RETROFIT_REQUIRED=NO'
  'AF_KNOWN_FUTURE_RUNTIME_INTEGRATION_LIMITATION=FROZEN_SERVER_HANDLER_STATUS_ONLY_EMPTY_BODY_SERIALIZATION'
  'AF_RESPONSE_PLAN_LAYOUT_HTTP1_RETROFIT=UNCHANGED_32_BYTES'
  'AF_RESPONSE_PLAN_NO_BODY_STATUSES=204_205_304'
  'AF_LEGACY_RESPONSE_PLAN_SERIALIZER_SUPPORTED_STATUSES=200_201_204_400_404_500'
  'AF_BROADER_FINAL_STATUS_SERIALIZATION=HTTP1_HTTP0_PATH_REQUIRED'
  'AF_HTTP1_CONTROLLED_SEMANTIC_RETROFIT=YES'
  'AF0_AF1_STATE=QUALIFIED_CANDIDATE_NOT_FROZEN'
)

for line in "${required[@]}"; do
  grep -Fqx "$line" "$CONTRACT" || { echo "FAIL: missing AF contract line: $line" >&2; exit 1; }
done

python3 - <<'PY'
from pathlib import Path
text = Path('docs/APPLICATION_DDD_MVC_FOUNDATION.md').read_text()
required = [
    'bidirectional runtime calls',
    'Three deterministic result channels',
    'Framework-to-application capability ABI',
    'Application-to-framework direction',
    'Frozen does not mean permanently immutable',
    'Current frozen-server integration boundary',
]
for item in required:
    if item not in text:
        raise SystemExit(f'FAIL: documentation section missing: {item}')
PY

git diff --check 2>/dev/null || true

echo 'PASS: AF0-AF1 foundation authority, bidirectional capability and controlled-retrofit contract'
