#!/usr/bin/env bash
set -euo pipefail

ROOT="${ARBORCORE_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
cd "$ROOT"
CONTRACT=application/arborcore-application-capability-kernel-1.contract
[[ -s "$CONTRACT" ]]

required=(
  'ARBORCORE_APPLICATION_CAPABILITY_KERNEL_VERSION=0.1-AF2-R1'
  'AF2_BASE_COMMIT=f5b98e824d367f20035823c8ef52f5bb08df9af7'
  'AF2_BASE_TREE=08817700443742297371794175259424cb0b0a91'
  'AF2_ARCHITECTURE=SHARED_BIDIRECTIONAL_CAPABILITY_MODULE_KERNEL'
  'AF2_CAPABILITY_VERSION=MAJOR_EXACT_MINOR_PROVIDER_GTE_REQUIRED'
  'AF2_MODULE_DESCRIPTOR_STRUCT_SIZE=EXACT_V1_SIZE'
  'AF2_INTERFACE_MODEL=VERSIONED_TYPED_FUNCTION_TABLE_PLUS_OPAQUE_PROVIDER_CONTEXT'
  'AF2_PROVIDER_CONTEXT_LIFETIME=PROVIDER_OWNED_BORROWED_OUTLIVES_CACHED_BINDING_USE'
  'AF2_TOPOLOGICAL_ORDER=PROVIDER_BEFORE_CONSUMER_CATALOG_INDEX_TIE_BREAK'
  'AF2_CATALOG_VALIDATE_ORDER=REQUIRE_CANONICAL_TIE_BREAK_ORDER'
  'AF2_DIRECT_QUALIFIED_LOWER_API_CALLS=PRESERVED_WHEN_LOOKUP_INDIRECTION_IS_UNNECESSARY'
  'AF2_UPPER_TO_LOWER=PUBLIC_DIRECT_API_OR_RESOLVED_TYPED_CAPABILITY'
  'AF2_LOWER_TO_UPPER=RESOLVED_REGISTERED_TYPED_CAPABILITY_CALLBACK_OR_FUNCTION_TABLE'
  'AF2_GLOBAL_MUTABLE_REGISTRY=ZERO'
  'AF2_HIDDEN_HEAP_ALLOCATION=ZERO'
  'AF2_PERSISTENT_PUBLICATION=CALLER_OWNED_TRANSACTIONAL_IMMUTABLE_AFTER_SUCCESS'
  'AF2_CATALOG_OUTPUT=UNCHANGED_ON_FAILURE'
  'AF2_PERSISTENT_STORAGE=UNCHANGED_ON_PREPARE_FAILURE'
  'AF2_STORAGE_ALIASING=PUBLICATION_WORKSPACE_OUTPUT_DISJOINT_FROM_EACH_OTHER_AND_IMMUTABLE_INPUT_REGIONS'
  'AF2_DOES_NOT_INVENT_UNQUALIFIED_SERVICE_ABIS=YES'
  'AF2_LOWER_LAYER_RETROFIT_REQUIRED=NO'
  'AF2_MARIADB=FROZEN'
  'AF2_R=FROZEN'
  'AF2_DEPLOYMENT=FROZEN'
)
for line in "${required[@]}"; do grep -Fqx "$line" "$CONTRACT"; done

grep -Fq 'u64_add_checked' src/c/capability_kernel.c
if grep -E '\b(malloc|calloc|realloc|free)[[:space:]]*\(' src/c/capability_kernel.c >/dev/null; then
  echo 'FAIL: AF2 kernel must not use hidden heap allocation' >&2
  exit 1
fi

grep -Fq 'arbor_application_capabilities' tests/c/application_capability_kernel_test.c
grep -Fq 'u64_add_checked' tests/c/application_capability_kernel_test.c

git diff --check

echo 'PASS: AF2 shared capability/module authority and bidirectional composition contract'
