#!/usr/bin/env bash
set -euo pipefail
ROOT="${ARBORCORE_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
cd "$ROOT"
CONTRACT=browser/arborcore-browser-v2-hardening-optimization-1.contract
[[ -s "$CONTRACT" ]]
required=(
  'ARBORCORE_BROWSER_V2_HARDENING_OPTIMIZATION_VERSION=1.0-R2.1'
  'BV2H_BASE_COMMIT=22c5476754b6adf35fd742dfac5c208fed46d2bc'
  'BV2H_PORTABLE_BROWSER_AUTHORITY=C_WASM'
  'BV2H_GPU_AUTHORITY=WGSL'
  'BV2H_JS_ROLE=BROWSER_HOST_SYSCALL_SHIM_ONLY'
  'BV2H_AUTHORITATIVE_JS_LOGIC=ZERO'
  'BV2H_TIMING_AGGREGATION_AUTHORITY=C_WASM'
  'BV2H_LIFECYCLE_AUTHORITY=C_WASM'
  'BV2H_OPT2_STATE=FROZEN_EXTENDED_QUALIFICATION'
  'BV2H_OPT3_STATE=QUALIFIED_TEST_ONLY_PROMISING_FUTURE_CONTRACT_REVISION'
  'BV2H_OPT3_PRODUCTION_ADMISSION=DEFERRED'
  'BV2H_OPT3_FIREFOX_EXACT_EQUIVALENCE=PASS'
  'BV2H_OPT3_FIREFOX_PERFORMANCE_SIGNAL=STRONG_POSITIVE'
  'BV2H_OPT3_CROSS_BROWSER_PRODUCTION_EVIDENCE=INSUFFICIENT'
  'BV2H_OPT3_CHROME_STATE=QUALIFIED_PLATFORM_FAILURE_EXTERNAL_INSTANCE_LOSS'
  'BV2H_WEBKIT_SAFARI_RELEASE_CLAIM=NOT_ADMITTED_UNTIL_FORMAL_QUALIFICATION'
  'BV2H_LIVE_EVIDENCE_BINDING=CANDIDATE_SOURCE_SHA256_AND_WASM_SHA256'
  'BV2H_REPRODUCIBILITY_ARCHIVE_INCLUDES_MAKEFILE=YES'
  'BV2H_REPRODUCIBILITY_ARCHIVE_FILE_COUNT=31'
  'BV2H_CONTRACT_STATE=FROZEN'
  'BV2H_DELIVERY_STATE=FROZEN_BV2H'
)
for line in "${required[@]}"; do grep -Fqx "$line" "$CONTRACT"; done
python3 tools/browser_v2_hardening_js_audit.py
[[ "$(sha256sum browser/arborcore_host.js | awk '{print $1}')" == c7fb40e47ec93796e1a68b44948b983b433ac67b152a628a02678eae297b9d4a ]]
git diff --check
echo 'PASS: frozen BV2H authority, OPT2, deferred OPT3 and R2.1 evidence-binding contract'
