#!/usr/bin/env bash

set -euo pipefail


RUNS=3

tmpdir="$(mktemp -d /tmp/arborcore-memory-qualify.XXXXXX)"

trap 'rm -rf "$tmpdir"' EXIT


iterations_for_size()
{
    local size="$1"

    if (( size <= 16 )); then
        echo 20000000
    elif (( size <= 64 )); then
        echo 10000000
    elif (( size <= 128 )); then
        echo 5000000
    else
        echo 3000000
    fi
}


build_benchmark()
{
    local function="$1"
    local size="$2"
    local iterations="$3"

    local object="$tmpdir/${function}-${size}.o"
    local executable="$tmpdir/${function}-${size}"

    if [[ ! -x "$executable" ]]; then

        nasm \
            -f elf64 \
            -Wall \
            -Wno-reloc-rel-dword \
            -Wno-reloc-abs-qword \
            -DCOPY_FUNCTION="$function" \
            -DCOPY_SIZE="$size" \
            -DITERATIONS="$iterations" \
            memory_bench.asm \
            -o "$object"

        ld \
            -o "$executable" \
            "$object" \
            memory.o \
            write.o
    fi

    printf '%s\n' "$executable"
}


measure()
{
    local function="$1"
    local size="$2"

    local iterations
    iterations="$(iterations_for_size "$size")"

    local executable
    executable="$(build_benchmark "$function" "$size" "$iterations")"

    local values=()

    local i

    for ((i = 0; i < RUNS; i++)); do

        values+=(
            "$(
                "$executable" |
                    od -An -tu8 |
                    tr -d '[:space:]'
            )"
        )

    done

    printf '%s\n' "${values[@]}" |
        sort -n |
        sed -n '2p'
}


wins_by_percent()
{
    local candidate="$1"
    local reference="$2"
    local percentage="$3"

    (( candidate * 100 <= reference * percentage ))
}


echo "### Arborcore memory qualification"
echo


# ============================================================
# Find scalar -> qword transition.
#
# Require qword to beat scalar by at least 10% at three
# consecutive byte sizes.
# ============================================================

qword_min=8

declare -A scalar_small
declare -A qword_small


for size in {1..16}; do

    scalar_small["$size"]="$(measure memory_copy_scalar "$size")"
    qword_small["$size"]="$(measure memory_copy_qword "$size")"

    printf \
        'small %2d: scalar=%s qword=%s\n' \
        "$size" \
        "${scalar_small[$size]}" \
        "${qword_small[$size]}"

done


for size in {1..14}; do

    if \
        wins_by_percent \
            "${qword_small[$size]}" \
            "${scalar_small[$size]}" \
            90 \
        && \
        wins_by_percent \
            "${qword_small[$((size + 1))]}" \
            "${scalar_small[$((size + 1))]}" \
            90 \
        && \
        wins_by_percent \
            "${qword_small[$((size + 2))]}" \
            "${scalar_small[$((size + 2))]}" \
            90
    then
        qword_min="$size"
        break
    fi

done


echo
echo "Selected qword minimum: $qword_min bytes"
echo


# ============================================================
# Find qword -> REP transition.
#
# Use multiples of eight so qword-tail costs do not distort
# the fundamental crossover.
#
# Require REP to beat qword by at least 5% at three
# consecutive tested sizes.
# ============================================================

declare -a rep_sizes=()

for ((size = 64; size <= 256; size += 8)); do
    rep_sizes+=("$size")
done


declare -A qword_large
declare -A rep_large


for size in "${rep_sizes[@]}"; do

    qword_large["$size"]="$(measure memory_copy_qword "$size")"
    rep_large["$size"]="$(measure memory_copy_rep "$size")"

    printf \
        'large %3d: qword=%s rep=%s\n' \
        "$size" \
        "${qword_large[$size]}" \
        "${rep_large[$size]}"

done


rep_min=256


for ((i = 0; i <= ${#rep_sizes[@]} - 3; i++)); do

    a="${rep_sizes[$i]}"
    b="${rep_sizes[$((i + 1))]}"
    c="${rep_sizes[$((i + 2))]}"

    if \
        wins_by_percent \
            "${rep_large[$a]}" \
            "${qword_large[$a]}" \
            95 \
        && \
        wins_by_percent \
            "${rep_large[$b]}" \
            "${qword_large[$b]}" \
            95 \
        && \
        wins_by_percent \
            "${rep_large[$c]}" \
            "${qword_large[$c]}" \
            95
    then
        rep_min="$a"
        break
    fi

done


echo
echo "Selected REP minimum: $rep_min bytes"


if (( rep_min <= qword_min )); then
    echo "FAIL: invalid generated thresholds" >&2
    exit 1
fi


mkdir -p generated

output="$(mktemp generated/memory_thresholds.inc.XXXXXX)"


cat > "$output" <<EOF
; Generated by Arborcore memory qualification.
;
; Do not manually tune these values.

%define MEMORY_COPY_QWORD_MIN $qword_min
%define MEMORY_COPY_REP_MIN   $rep_min
EOF


mv "$output" generated/memory_thresholds.inc


echo
echo "Generated:"
cat generated/memory_thresholds.inc
