#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
source "$ROOT/tools/server_benchmark_common.sh"

# Qualification is intentionally stronger than the quick benchmark.
export ARBORCORE_BENCH_RUNS="${ARBORCORE_BENCH_RUNS:-31}"
export ARBORCORE_BENCH_WARMUPS="${ARBORCORE_BENCH_WARMUPS:-3}"
PROFILE="$(arborcore_perf_profile)"
export ARBORCORE_BENCH_OUT_DIR="${ARBORCORE_BENCH_OUT_DIR:-$ROOT/build/server-baseline-qualification-$PROFILE}"

bash "$ROOT/tools/server_benchmark_run.sh"

SUMMARY="$ARBORCORE_BENCH_OUT_DIR/summary.tsv"
BASELINE="$(arborcore_perf_baseline_path "$ROOT")"
mkdir -p "$ROOT/generated/performance"

cpu="$(arborcore_bench_cpu)"
text_bytes="$(arborcore_production_text_bytes "$ROOT")"

{
    echo '# Arborcore machine-specific server performance baseline.'
    echo '# Generated by tools/server_baseline_qualify.sh.'
    echo '# This is one proposed qualification round; accept-server-baseline'
    echo '# combines three independent rounds before enabling regression failure.'
    echo 'BASELINE_VERSION=3'
    printf 'PERFORMANCE_PROFILE=%s\n' "$PROFILE"
    echo 'POLICY_STATE=PROPOSED'
    printf 'PRODUCTION_COMMIT=%s\n' "$(git -C "$ROOT" rev-parse HEAD)"
    printf 'PRODUCTION_TEXT_BYTES=%s\n' "$text_bytes"
    printf 'BENCH_CPU=%s\n' "$cpu"
    printf 'BENCH_RUNS=%s\n' "$ARBORCORE_BENCH_RUNS"
    printf 'BENCH_WARMUPS=%s\n' "$ARBORCORE_BENCH_WARMUPS"
    printf 'KERNEL=%q\n' "$(uname -srmo)"
    printf 'ARCHITECTURE=%s\n' "$(arborcore_architecture)"
    printf 'CPU_MODEL=%q\n' "$(arborcore_cpu_model)"
    printf 'CPU_SCALING_DRIVER=%s\n' "$(arborcore_scaling_driver)"
    if [[ -r /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor ]]; then
        printf 'CPU_GOVERNOR=%s\n' "$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)"
    fi

    tail -n +2 "$SUMMARY" | while IFS=$'\t' read -r \
        metric samples median mad mad_pct p90 p95 p99 min max ops p95slow
    do
        key="$(printf '%s' "$metric" | tr '[:lower:]-' '[:upper:]_')"
        printf '%s_SAMPLES=%s\n' "$key" "$samples"
        printf '%s_MEDIAN_NS_PER_OP=%s\n' "$key" "$median"
        printf '%s_MAD_NS_PER_OP=%s\n' "$key" "$mad"
        printf '%s_MAD_PCT=%s\n' "$key" "$mad_pct"
        printf '%s_RUN_P90_NS_PER_OP=%s\n' "$key" "$p90"
        printf '%s_RUN_P95_NS_PER_OP=%s\n' "$key" "$p95"
        printf '%s_RUN_P99_NS_PER_OP=%s\n' "$key" "$p99"
        printf '%s_MEDIAN_OPS_PER_SEC=%s\n' "$key" "$ops"
        printf '%s_RUN_P95_SLOW_PCT=%s\n' "$key" "$p95slow"
    done
} > "$BASELINE"

echo
echo "### PROPOSED SERVER BASELINE"
cat "$BASELINE"
echo
echo "Baseline written to: $BASELINE"
echo "Policy remains PROPOSED until three independent qualification rounds are accepted."
