#!/usr/bin/env bash
set -euo pipefail
ROOT="${ARBORCORE_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
cd "$ROOT"
contract=view/arborcore-view-core-1.contract

for item in \
 'VIEW0_PUBLIC_FUNCTION_COUNT=11' \
 'VIEW0_V1_D1_MANUALS_EXAMPLES_MUST_PASS=YES' \
 'VIEW0_V1_CONTENT_TYPE_SINGLETON_MANUAL_OBLIGATION=CARRIED_FORWARD' \
 'VIEW0_V1_C4_ASSEMBLY_CONSUMER_STABILITY_PROMISE_OBLIGATION=CARRIED_FORWARD' \
 'VIEW0_D1_AFTER_V1N4=MANUALS_RUNNABLE_EXAMPLES_DOC_CONSISTENCY_GATE' \
 'VIEW0_D1_CONTRACT_REVISION=0.1-VIEW0-D1' \
 'VIEW0_D1_SCOPE=CANONICAL_MANUALS_RUNNABLE_FILE_BASED_EXAMPLES_AND_DOCUMENTATION_CONSISTENCY_GATE' \
 'VIEW0_D1_PREDECESSOR_V1N4_COMMIT=f72d01785bd1b147f940e17e5c3871f00265c574' \
 'VIEW0_D1_PREDECESSOR_V1N4_TREE=0b5b631b3915239c205b773f623e2c6660ecf35d' \
 'VIEW0_D1_MANUALS=DOCS_VIEW_CORE_VIEW0_AND_EXAMPLES_VIEW0_README' \
 'VIEW0_D1_RUNNABLE_EXAMPLE_ROOT=examples/view0' \
 'VIEW0_D1_TEMPLATE_SOURCE_FILE=examples/view0/page.html' \
 'VIEW0_D1_RENDERER_MODES=T1_FILE_TEMPLATE_C3_NATIVE_C_C4_NASM' \
 'VIEW0_D1_GENERATED_DOCUMENT_COUNT=3' \
 'VIEW0_D1_GENERATED_DOCUMENT_BYTE_EQUIVALENCE=REQUIRED' \
 'VIEW0_D1_GENERATED_DOCUMENT_UTF8_VALIDATION=REQUIRED' \
 'VIEW0_D1_V1_CONFORMANCE_CHECKER=CURRENT_NATIVE_V1N4_BOUNDED_104_RULE_TOOL' \
 'VIEW0_D1_V1_CONFORMANCE_ZERO_DIAGNOSTICS=REQUIRED' \
 'VIEW0_D1_V1_CONFORMANCE_ZERO_TOKENIZER_ERRORS=REQUIRED' \
 'VIEW0_D1_V1_CONFORMANCE_ZERO_TREE_ERRORS=REQUIRED' \
 'VIEW0_D1_V1_CONFORMANCE_PARSE_CLEAN=REQUIRED' \
 'VIEW0_D1_COMPLETE_HTML_CONFORMANCE_CLAIM=NO' \
 'VIEW0_D1_COMPLETE_ECMASCRIPT_CONFORMANCE_CLAIM=NO' \
 'VIEW0_D1_M1_PUBLICATION_SEQUENCE=RENDER_VALIDATE_UTF8_MAKE_PLAN_APPEND_CONTENT_TYPE_PUBLISH_PLAN' \
 'VIEW0_D1_CONTENT_TYPE_SINGLETON_NAME=Content-Type' \
 'VIEW0_D1_CONTENT_TYPE_SINGLETON_VALUE=text/html; charset=utf-8' \
 'VIEW0_D1_CONTENT_TYPE_SINGLETON_OWNER=PRESENTER_VIA_HTTP1_RESPONSE_FIELD_SIDECAR' \
 'VIEW0_D1_CONTROLLER_OR_MIDDLEWARE_PREADD_CONTENT_TYPE=COMPOSITION_PRECONDITION_VIOLATION' \
 'VIEW0_D1_HTTP1_DUPLICATE_FIELD_SEMANTICS_REOPEN=NO' \
 'VIEW0_D1_M1_REAL_SOCKET_REGRESSION=REQUIRED' \
 'VIEW0_D1_C4_REAL_NASM_ABI_REGRESSION=REQUIRED' \
 'VIEW0_D1_C4_ASSEMBLY_CONSUMER=APPLICATION_STYLE_EXISTING_VIEW_C_API' \
 'VIEW0_D1_ASSEMBLY_ABI_V1_REOPEN=NO' \
 'VIEW0_D1_PRODUCTION_ASSEMBLY_SYMBOL_ADDITION=ZERO' \
 'VIEW0_D1_PRODUCTION_VIEW_API_CHANGE=NO' \
 'VIEW0_D1_TOTAL_PUBLIC_FUNCTION_COUNT=11' \
 'VIEW0_D1_NEW_PRESENTER_FRAMEWORK=NO' \
 'VIEW0_D1_REQUEST_TIME_HTML_VALIDATOR=NO' \
 'VIEW0_D1_SECOND_HTML_PARSER=NO' \
 'VIEW0_D1_BROWSER_AUTHORITY_REOPEN=NO' \
 'VIEW0_D1_AF1_AF4_REOPEN=NO' \
 'VIEW0_D1_MVC0_REOPEN=NO' \
 'VIEW0_D1_HTTP0_REOPEN=NO' \
 'VIEW0_D1_HTTP1_REOPEN=NO' \
 'VIEW0_D1_DATABASE_DEPENDENCY=NONE' \
 'VIEW0_D1_R_DEPENDENCY=NONE' \
 'VIEW0_D1_DOCUMENTATION_CONSISTENCY=REQUIRED' \
 'VIEW0_D1_GATE=MANUALS_EXAMPLES_NATIVE_V1_M1_C4_DOCUMENTATION_CONSISTENCY' \
 'VIEW0_D1_ADMISSION=YES_POST_INDEPENDENT_REVIEW_AND_FREEZE'; do
  grep -Fxq "$item" "$contract" || { echo "FAIL: missing D1 contract marker: $item" >&2; exit 1; }
done

count=$(grep -Ec '^arbor_status arbor_view_[a-z0-9_]+\(' include/arborcore/view.h)
[[ "$count" -eq 11 ]] || { echo "FAIL: D1 must retain 11 public VIEW functions, got $count" >&2; exit 1; }

# D1 must not create a new production framework or ABI surface.
! grep -Rq 'arborcore_view0_d1_' include src || { echo 'FAIL: D1 example symbol leaked into production include/src' >&2; exit 1; }
grep -Fxq 'VIEW0_V1N4_REVIEW_COMPLETION=YES' "$contract"
grep -Fxq 'VIEW0_V1N4_COMPLETE_HTML_CONFORMANCE_CLAIM=NO' "$contract"

echo 'VIEW0_D1_TOTAL_PUBLIC_FUNCTION_COUNT=11'
echo 'VIEW0_D1_ASSEMBLY_ABI_V1_REOPEN=NO'
echo 'VIEW0_D1_COMPLETE_HTML_CONFORMANCE_CLAIM=NO'
echo 'PASS: VIEW0 D1 contract and frozen-boundary preservation'
