#!/usr/bin/env bash
set -euo pipefail
ROOT="${ARBORCORE_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"; cd "$ROOT"
contract=view/arborcore-view-core-1.contract
header=include/arborcore/view.h
source=src/c/view.c
doc=docs/VIEW_CORE_VIEW0.md
for item in \
 'VIEW0_C3_CONTRACT_REVISION=0.1-VIEW0-C3-R1' \
 'VIEW0_C3_SCOPE=NATIVE_C_COMPILED_VIEW_PATH' \
 'VIEW0_C3_PUBLIC_FUNCTION_COUNT=0' \
 'VIEW0_C3_TOTAL_PUBLIC_FUNCTION_COUNT=7' \
 'VIEW0_C3_PRODUCTION_VIEW_SOURCE_CHANGE=NO' \
 'VIEW0_C3_PRODUCTION_VIEW_HEADER_CHANGE=NO' \
 'VIEW0_C3_ABSTRACTION=APPLICATION_DEFINED_TYPED_C_FUNCTION_COMPOSING_C1_C2' \
 'VIEW0_C3_GENERIC_VOID_MODEL_CALLBACK=NOT_INTRODUCED' \
 'VIEW0_C3_MODEL_TYPE=APPLICATION_DEFINED_TYPED_STRUCT' \
 'VIEW0_C3_MODEL_SOURCE_SNAPSHOT=NO' \
 'VIEW0_C3_MODEL_STABILITY_DURING_RENDER=CALLER_REQUIRED' \
 'VIEW0_C3_ALIAS_VALIDATION=APPLICATION_DEFINED_TYPED_VIEW_RESPONSIBILITY' \
 'VIEW0_C3_MODEL_CONTAINER_ALIAS_POLICY=REJECT_MUTABLE_ARENA_METADATA_OR_FITTING_FUTURE_BODY_RESERVATION' \
 'VIEW0_C3_RESULT_ALIAS_POLICY=REJECT_MODEL_CONTAINER_OR_BORROWED_MODEL_SPANS' \
 'VIEW0_C3_PRIOR_SAME_ARENA_MODEL_SOURCE=ALLOW_NONOVERLAPPING_FUTURE_OUTPUT' \
 'VIEW0_C3_CAPACITY_PRECEDENCE=NO_SPECULATIVE_FUTURE_RESERVATION_ALIAS_WHEN_BODY_CANNOT_FIT' \
 'VIEW0_C3_TWO_PASS_OPERATION=MEASURE_THEN_RENDER_SYNCHRONOUS' \
 'VIEW0_C3_RESPONSE_PUBLICATION=C1_COMMIT_ONLY' \
 'VIEW0_C3_APPLICATION_FAILURE_AFTER_BEGIN=EXPLICIT_ABORT_REQUIRED_IF_NOT_ALREADY_ROLLED_BACK' \
 'VIEW0_C3_BODY_STORAGE=REQUEST_ARENA' \
 'VIEW0_C3_PARTIAL_BODY_PUBLICATION_ON_FAILURE=NO' \
 'VIEW0_C3_FIXED_EXTERNAL_CSS_REFERENCE=TRUSTED_STATIC_HTML_ALLOWED' \
 'VIEW0_C3_DYNAMIC_CSS_INTERPOLATION=NOT_ADMITTED' \
 'VIEW0_C3_USER_FACING_HTTP_ADMISSION=NOT_YET' \
 'VIEW0_C3_UTF8_INTEGRATION_GATE=DEFERRED_TO_M1' \
 'VIEW0_C3_DATABASE_DEPENDENCY=NONE'; do
  grep -Fxq "$item" "$contract" || { echo "FAIL: missing C3 contract marker: $item" >&2; exit 1; }
done
count=$(grep -Ec '^arbor_status arbor_view_[a-z0-9_]+\(' "$header")
[[ "$count" -ge 7 ]] || { echo "FAIL: cumulative VIEW public surface lost C1/C2 functions; got $count" >&2; exit 1; }
grep -Fq 'ordinary application-defined,' "$doc"
grep -Fq 'C3 deliberately adds no generic renderer' "$doc"
grep -Fq 'must call' "$doc"
grep -Fq '`arbor_view_output_abort()` explicitly' "$doc"
grep -Fq 'cross-role alias policy' "$doc"
grep -Fq 'ordinary C1 capacity' "$doc"
grep -Eq '^ARBORCORE_VIEW_CORE_VERSION=0\.1-VIEW0-' "$contract" || { echo 'FAIL: cumulative VIEW contract version missing' >&2; exit 1; }
echo 'VIEW0_C3_EXTENSION_AWARE_CONTRACT=YES'
echo 'VIEW0_C3_PUBLIC_FUNCTION_COUNT=0'
echo "VIEW0_TOTAL_PUBLIC_FUNCTION_COUNT=$count"
echo 'VIEW0_C3_REQUIRED_C1_C2_API_PRESENT=YES'
echo 'PASS: VIEW0 C3 typed native compiled-view composition adds no unnecessary production API'
